CREATE TABLE [dbo].[Products] (
    [ProductID]       INT          IDENTITY (1, 1) NOT NULL,
    [ProductName]     VARCHAR (50) NOT NULL,
    [ProductCode] VARCHAR(50) NULL, 
    [SupplierID]      INT          NULL,
    [CategoryID]      INT          NOT NULL,
    [QuantityPerUnit] VARCHAR (20) NULL,
    [UnitPrice]       MONEY        CONSTRAINT [DF_Products_UnitPrice] DEFAULT ((0)) NULL,
	[UnitSalePrice]   MONEY        CONSTRAINT [DF_Products_UnitSalePrice] DEFAULT ((0)) NULL,
    [UnitsInStock]    INT     CONSTRAINT [DF_Products_UnitsInStock] DEFAULT ((0)) NULL,
    [UnitsOnOrder]    INT     CONSTRAINT [DF_Products_UnitsOnOrder] DEFAULT ((0)) NULL,
    [ReorderLevel]    INT     CONSTRAINT [DF_Products_ReorderLevel] DEFAULT ((0)) NULL,
    [Discontinued]    BIT          CONSTRAINT [DF_Products_Discontinued] DEFAULT ((0)) NOT NULL,
    [StatusId] INT NULL, 
    [Notes] VARCHAR(2048) NULL, 
    [CreatedDate] DATETIME NULL, 
    [UpdatedDate] DATETIME NULL, 
    [CreatedBy] VARCHAR(50) NULL, 
    [UpdatedBy] VARCHAR(50) NULL, 
    CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED ([ProductID] ASC),
    CONSTRAINT [CK_Products_UnitPrice] CHECK ([UnitPrice]>=(0)),
    CONSTRAINT [CK_ReorderLevel] CHECK ([ReorderLevel]>=(0)),
    CONSTRAINT [CK_UnitsInStock] CHECK ([UnitsInStock]>=(0)),
    CONSTRAINT [CK_UnitsOnOrder] CHECK ([UnitsOnOrder]>=(0)),
    CONSTRAINT [FK_Products_Categories] FOREIGN KEY ([CategoryID]) REFERENCES [dbo].[Categories] ([CategoryID]),
    CONSTRAINT [FK_Products_Suppliers] FOREIGN KEY ([SupplierID]) REFERENCES [dbo].[Suppliers] ([SupplierID])
);

